**Aggregation in TensorFlow**

In [23]:
import tensorflow as tf

In [24]:
t1 = tf.constant([-8,-3])
t2 = tf.constant([10,7])

In [25]:
tf.abs(t1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([8, 3], dtype=int32)>

In [26]:
t1

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-8, -3], dtype=int32)>

In [27]:
#aggreagtions
import numpy as np

In [28]:
t3= tf.constant(np.random.randint(0,200,size=30), dtype=tf.float32)

In [29]:
t3.numpy()

array([147.,  27., 164.,  98., 133.,  22., 176., 113.,  49.,  96., 105.,
        27.,  37.,  93.,  33.,   4., 161., 101., 185.,  52.,  45.,  27.,
       123.,  14.,  41.,  13., 161., 182.,  12.,  20.], dtype=float32)

In [30]:
tf.size(t3), t3.shape, t3.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=30>, TensorShape([30]), 1)

In [31]:
tf.reduce_min(t3)

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [32]:
np.min(t3)

4.0

In [33]:
tf.reduce_max(t3)

<tf.Tensor: shape=(), dtype=float32, numpy=185.0>

In [34]:
np.max(t3)

185.0

In [35]:
tf.reduce_mean(t3)

<tf.Tensor: shape=(), dtype=float32, numpy=82.03333>

In [36]:
np.mean(t3)

82.03333

In [37]:
tf.reduce_sum(t3)

<tf.Tensor: shape=(), dtype=float32, numpy=2461.0>

In [38]:
np.sum(t3)

2461.0

In [39]:
tf.math.reduce_std(t3)  #standard deviation using tf

<tf.Tensor: shape=(), dtype=float32, numpy=59.42361>

In [40]:
np.std(t3)  #using numpy

59.42361

In [43]:
tf.math.reduce_variance(t3)   #variance using tf

<tf.Tensor: shape=(), dtype=float32, numpy=3531.1655>

In [44]:
np.var(t3)  #using numpy

3531.1653

In [50]:
tf.argmax(t3)

<tf.Tensor: shape=(), dtype=int64, numpy=18>

In [51]:
tf.argmin(t3)

<tf.Tensor: shape=(), dtype=int64, numpy=15>

In [45]:
#type casting
tf.math.reduce_variance(tf.cast(t3,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=3531.1655>

In [46]:
tf.random.set_seed(42)
t4 = tf.random.uniform(shape=[30])
t4

<tf.Tensor: shape=(30,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173],
      dtype=float32)>

In [47]:
tf.argmax(t4)

<tf.Tensor: shape=(), dtype=int64, numpy=15>

In [49]:
t4[tf.argmax(t4)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.8996835>

In [52]:
tf.argmin(t4)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

**Sqeezing Tensor**

In [53]:
tf.squeeze(t4)

<tf.Tensor: shape=(30,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173],
      dtype=float32)>

In [57]:
tf.random.set_seed(42)
t5 = tf.constant(tf.random.uniform(shape=[30]),shape=(1,1,1,30))
t5.numpy()

array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173]]]],
      dtype=float32)

In [56]:
t6 = tf.squeeze(t5)
t6

<tf.Tensor: shape=(30,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173],
      dtype=float32)>