**Activation Functions:** They help neural networks learn and make sense of complex data.

An activation function in a neural network decides whether a neuron should be activated or not.
It introduces non-linearity into the model, allowing it to learn complex patterns and relationships in data.

Without activation functions, a neural network would behave like a linear model, limiting its ability to capture intricate patterns.

Common activation functions include ReLU, Leaky ReLU, Softmax, and Softplus, each serving a specific purpose in the network's learning process.

In [ ]:
import tensorflow as tf

In [ ]:
x = tf.constant([-2.0,-1.0, 0.0, 1.0, 2.0])

In [ ]:
# Apply ReLU activation
relu_x = tf.nn.relu(x)

In [ ]:
print(relu_x)

tf.Tensor([0. 0. 0. 1. 2.], shape=(5,), dtype=float32)


**Purpose**: **ReLU** is one of the most popular activation functions. It replaces negative values with zero and keeps positive values unchanged.

In [ ]:
x = tf.constant([-1.0, 0.0, 1.0, 2.0])

In [ ]:
# Apply Leaky ReLU activation with a negative slope (alpha)
leaky_relu_x = tf.nn.leaky_relu(x, alpha=0.2)

In [ ]:
print(leaky_relu_x)

tf.Tensor([-0.2  0.   1.   2. ], shape=(4,), dtype=float32)


**Purpose**: **Leaky ReLU** is similar to ReLU, but it allows a small, non-zero gradient for negative values. This can help with training by avoiding dead neurons.

In [ ]:
logits = tf.constant([2.0, 1.0, 0.1]) #tensor with logits

In [ ]:
softmax_x = tf.keras.layers.Softmax()(logits)

In [ ]:
print(softmax_x)

tf.Tensor([0.6590012  0.24243298 0.09856589], shape=(3,), dtype=float32)


**Purpose**: **Softmax** converts raw scores (logits) into probabilities. It’s typically used in the output layer of a classification model to predict class probabilities.

In [ ]:
x = tf.constant([-2.0,-1.0, 0.0, 1.0, 2.0])

In [ ]:
softplus_x = tf.nn.softplus(x)

In [ ]:
print(softmax_x)

tf.Tensor([0.6590012  0.24243298 0.09856589], shape=(3,), dtype=float32)


**Purpose**: **Softplus** is a smooth approximation to the ReLU function. It’s useful for creating a differentiable alternative to ReLU.

### **Summary:**

tf.nn.relu(): Simple and widely used; turns negative values to 0.

tf.nn.leaky_relu(): Similar to ReLU, but allows a small gradient for negative values.

tf.keras.layers.Softmax: Converts logits to probabilities for classification tasks.

tf.nn.softplus(): A smooth version of ReLU, useful for continuous transitions.

In [ ]:
#another example
t1 = tf.constant([-3.5, -2.0, 0.5, 1.5, 3.0])

# Apply ReLU activation
relu_x = tf.nn.relu(t1)

In [ ]:
relu_x.numpy()

array([0. , 0. , 0.5, 1.5, 3. ], dtype=float32)

In [ ]:
t2 = tf.constant([-4.5, -3.0, 0.6, 1.8, 3.5])

# Apply Leaky ReLU activation with a small slope (alpha)
leaky_relu_x = tf.nn.leaky_relu(t2, alpha=0.5)

In [ ]:
leaky_relu_x.numpy()

array([-2.25, -1.5 ,  0.6 ,  1.8 ,  3.5 ], dtype=float32)

In [ ]:
t3 = tf.constant([8.0, 1.0, 0.5])

# Apply Softmax activation
softmax_x = tf.nn.softmax(t3)

In [ ]:
softmax_x.numpy()

array([9.985372e-01, 9.105480e-04, 5.522753e-04], dtype=float32)

In [ ]:
t4 = tf.constant([-3.5, -2.0, 0.5, 1.5, 3.0])

# Apply Softplus activation
softplus_x = tf.nn.softplus(t4)

In [ ]:
softplus_x.numpy()

array([0.02975042, 0.126928  , 0.974077  , 1.7014133 , 3.0485873 ],
      dtype=float32)