**ModelCheckpoint is a callback used during the training process of a Keras model.**

In [63]:
import tensorflow as tf

# Example: Simple Sequential Model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(76, activation= None, input_shape=(1,)),
    tf.keras.layers.Dense(1)
])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [64]:
# Compile the model
model.compile(optimizer=tf.keras.optimizers.Adamax(learning_rate=0.001), loss= tf.keras.losses.MeanAbsoluteError(), metrics=['mae'])

In [65]:
# Define the ModelCheckpoint callback with .keras extension
checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath = 'model.keras',
    save_best_only = True,
    monitor = 'val_loss',
    mode ='min',
    verbose = 1
)


**Key Parameters:**

**filepath**: The path where the model or weights will be saved. This can include placeholders like {epoch} or {val_loss} to include the epoch number or metric value in the filename.

**save_best_only**: If True, the model will only be saved when the monitored metric improves. This helps ensure you only keep the best version of the model.

**monitor**: The metric to monitor, such as 'val_loss' or 'val_accuracy'. This is the metric that determines whether the model should be saved or not.

**mode**: Determines whether to look for the maximum or minimum value of the monitored metric. Use 'min' for metrics like loss (where lower is better) and 'max' for metrics like accuracy (where higher is better).

**verbose**: If 1, it prints messages about model saving. If 0, it is silent.

In [66]:
x = tf.range(1,101,4)
x

<tf.Tensor: shape=(25,), dtype=int32, numpy=
array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97], dtype=int32)>

In [67]:
y = 2*x + 3

In [68]:
y

<tf.Tensor: shape=(25,), dtype=int32, numpy=
array([  5,  13,  21,  29,  37,  45,  53,  61,  69,  77,  85,  93, 101,
       109, 117, 125, 133, 141, 149, 157, 165, 173, 181, 189, 197],
      dtype=int32)>

In [69]:
x = tf.cast(tf.constant(x), dtype = tf.float32)
y = tf.cast(tf.constant(y), dtype = tf.float32)

In [70]:
model.fit(x,y, epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 962ms/step - loss: 99.7432 - mae: 99.7432
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 98.6701 - mae: 98.6701
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 97.6001 - mae: 97.6001
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 96.5333 - mae: 96.5333
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 95.4696 - mae: 95.4696
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 94.4087 - mae: 94.4087
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 93.3507 - mae: 93.3507
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 92.2955 - mae: 92.2955
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 91.2428 - mae: 91.2428
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 90.1926 - mae: 90.1926
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 89.1448 - mae: 89.1448
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 88.0992 - mae: 88.0992
Epoch 13/500
1/1 ━━━━━━━

In [73]:
import numpy as np
predict = model.predict(np.array([5.0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step


In [74]:
predict

array([[12.989943]], dtype=float32)

In [76]:
predict = model.predict(np.array([10.0]))
predict

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step


array([[22.980837]], dtype=float32)