**Numerical Operations on Tensors:**

In [2]:
import tensorflow as tf

# Create two tensors
tensor_a = tf.constant([2, 4, 5])
tensor_b = tf.constant([5, 5, 4])

# Add the tensors
added_tensor = tf.add(tensor_a, tensor_b)
print("Added Tensor:")
print(added_tensor)


Added Tensor:
tf.Tensor([7 9 9], shape=(3,), dtype=int32)


In [3]:
# Subtract tensor_b from tensor_a
subtracted_tensor = tf.subtract(tensor_a, tensor_b)
print("\nSubtracted Tensor:")
print(subtracted_tensor)



Subtracted Tensor:
tf.Tensor([-3 -1  1], shape=(3,), dtype=int32)


In [4]:
# Multiply the tensors
multiplied_tensor = tf.multiply(tensor_a, tensor_b)
print("\nMultiplied Tensor:")
print(multiplied_tensor)



Multiplied Tensor:
tf.Tensor([10 20 20], shape=(3,), dtype=int32)


In [5]:
# Divide tensor_a by tensor_b
divided_tensor = tf.divide(tensor_a, tensor_b)
print("\nDivided Tensor:")
print(divided_tensor)



Divided Tensor:
tf.Tensor([0.4  0.8  1.25], shape=(3,), dtype=float64)


**What This Code Does:**

**Addition:** Adds tensor_a and tensor_b.

**Subtraction:** Subtracts tensor_b from tensor_a.

**Multiplication:** Multiplies tensor_a by tensor_b.

**Division:** Divides tensor_a by tensor_b.

 **Modulus Function:** Computes the remainder of division between two tensors, useful for cyclic operations and wrapping values.

 **Absolute Function:** Returns the absolute value of each element in a tensor, ensuring all values are non-negative.

In [6]:
# Compute the remainder of tensor_a divided by tensor_b
modulus_tensor = tf.math.mod(tensor_a, tensor_b)
print("\nModulus Tensor (A % B):", modulus_tensor)



Modulus Tensor (A % B): tf.Tensor([2 4 1], shape=(3,), dtype=int32)


In [7]:
# Compute the absolute value of tensor_a (useful if tensor_a contains negative values)
absolute_tensor = tf.abs(tensor_a)
print("\nAbsolute Value of Tensor A:", absolute_tensor)



Absolute Value of Tensor A: tf.Tensor([2 4 5], shape=(3,), dtype=int32)


In [8]:
# Create two tensors with different values
tensor_a = tf.constant([10, 20, 30])
tensor_b = tf.constant([5, 10, 15])

# Perform numerical operations on the tensors
added_tensor = tf.add(tensor_a, tensor_b)
subtracted_tensor = tf.subtract(tensor_a, tensor_b)
multiplied_tensor = tf.multiply(tensor_a, tensor_b)
divided_tensor = tf.divide(tensor_a, tensor_b)

# Print the results
print("Original Tensors:")
print("Tensor A:", tensor_a)
print("Tensor B:", tensor_b)

print("\nResults of Operations:")
print("Added Tensor:", added_tensor)
print("Subtracted Tensor:", subtracted_tensor)
print("Multiplied Tensor:", multiplied_tensor)
print("Divided Tensor:", divided_tensor)


Original Tensors:
Tensor A: tf.Tensor([10 20 30], shape=(3,), dtype=int32)
Tensor B: tf.Tensor([ 5 10 15], shape=(3,), dtype=int32)

Results of Operations:
Added Tensor: tf.Tensor([15 30 45], shape=(3,), dtype=int32)
Subtracted Tensor: tf.Tensor([ 5 10 15], shape=(3,), dtype=int32)
Multiplied Tensor: tf.Tensor([ 50 200 450], shape=(3,), dtype=int32)
Divided Tensor: tf.Tensor([2. 2. 2.], shape=(3,), dtype=float64)


**Float values:**

In [9]:
# Create two tensors with float values
tensor_a = tf.constant([1.5, 2.8, 3.1])
tensor_b = tf.constant([4.2, 5.3, 6.6])
# Perform numerical operations on the tensors
added_tensor = tf.add(tensor_a, tensor_b)
subtracted_tensor = tf.subtract(tensor_a, tensor_b)
multiplied_tensor = tf.multiply(tensor_a, tensor_b)
divided_tensor = tf.divide(tensor_a, tensor_b)
# Print the results
print("Original Tensors:")
print("Tensor A:", tensor_a)
print("Tensor B:", tensor_b)
print("\nResults of Operations:")
print("Added Tensor:", added_tensor.numpy())
print("Subtracted Tensor:", subtracted_tensor.numpy())
print("Multiplied Tensor:", multiplied_tensor.numpy())
print("Divided Tensor:", divided_tensor.numpy())

Original Tensors:
Tensor A: tf.Tensor([1.5 2.8 3.1], shape=(3,), dtype=float32)
Tensor B: tf.Tensor([4.2 5.3 6.6], shape=(3,), dtype=float32)

Results of Operations:
Added Tensor: [5.7 8.1 9.7]
Subtracted Tensor: [-2.6999998 -2.5000002 -3.5      ]
Multiplied Tensor: [ 6.2999997 14.84      20.46     ]
Divided Tensor: [0.35714287 0.52830184 0.46969697]
