In [1]:
import tensorflow as tf

 **A TensorFlow Variable is a mutable tensor that can hold and update values during model training.**

 **It is used to store and modify parameters of the model.**

In [2]:

# Create a TensorFlow variable directly with initial values
variable_tensor = tf.Variable([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], dtype=tf.float32)
print("Initial Variable Tensor:\n", variable_tensor.numpy())

Initial Variable Tensor:
 [1. 2. 3. 4. 5. 6.]


In [3]:
# Alter the variable tensor values using assign()

variable_tensor.assign([10.0, 20.0, 30.0, 40.0, 50.0, 60.0])
print("\nVariable Tensor After Assigning New Values:\n", variable_tensor.numpy())


Variable Tensor After Assigning New Values:
 [10. 20. 30. 40. 50. 60.]


In [4]:
#another example

variable_tensor1 = tf.Variable([10, 20, 30, 40, 50], dtype=tf.int32)
variable_tensor2 = tf.Variable([1, 2, 3, 4, 5], dtype=tf.int32)
print("Variable Tensor 1:\n", variable_tensor1.numpy())
print("Variable Tensor 2:\n", variable_tensor2.numpy())

Variable Tensor 1:
 [10 20 30 40 50]
Variable Tensor 2:
 [1 2 3 4 5]


**Mathematical operations on the two variables:**

In [5]:
# Addition
added_tensor = tf.add(variable_tensor1, variable_tensor2)
print("\nTensor After Addition:\n", added_tensor.numpy())


Tensor After Addition:
 [11 22 33 44 55]


In [6]:
# Subtraction
subtracted_tensor = tf.subtract(variable_tensor1, variable_tensor2)
print("\nTensor After Subtraction:\n", subtracted_tensor.numpy())




Tensor After Subtraction:
 [ 9 18 27 36 45]


In [7]:
# Multiplication
multiplied_tensor = tf.multiply(variable_tensor1, variable_tensor2)
print("\nTensor After Multiplication:\n", multiplied_tensor.numpy())


Tensor After Multiplication:
 [ 10  40  90 160 250]


In [8]:
# Division
divided_tensor = tf.divide(variable_tensor1, variable_tensor2)
print("\nTensor After Division:\n", divided_tensor.numpy())


Tensor After Division:
 [10. 10. 10. 10. 10.]


**Create a new tensor with random values:**

In [9]:
random_tensor = tf.random.uniform([6], minval=0, maxval=10, dtype=tf.int32)
print("\nRandom Tensor:\n", random_tensor.numpy())


Random Tensor:
 [5 6 0 0 8 6]


**Shuffle the random tensor values:**

In [10]:
shuffled_tensor = tf.random.shuffle(random_tensor)
print("\nShuffled Random Tensor:\n", shuffled_tensor.numpy())


Shuffled Random Tensor:
 [5 0 0 6 8 6]
