In [ ]:
import tensorflow as tf

### **The `tf.zeros` function creates a tensor filled with zeros, defined by a specific shape and data type.**

In [ ]:
#zeros tensor i.e. 2d
zeros_tensor_2d= tf.zeros([3,5])
print("zeros tensor: \n",zeros_tensor_2d.numpy())

zeros tensor: 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#attributes of tensors 2d
print("\nAttributes of Zeros Tensor:")
print("Number of Dimensions (ndim):", zeros_tensor_2d.ndim)
print("Shape:", zeros_tensor_2d.shape)
print("Number of Elements:", tf.size(zeros_tensor_2d).numpy())
print("Data Type:", zeros_tensor_2d.dtype)
print("Rank (using tf.rank):", tf.rank(zeros_tensor_2d).numpy())


Attributes of Zeros Tensor:
Number of Dimensions (ndim): 2
Shape: (3, 5)
Number of Elements: 15
Data Type: <dtype: 'float32'>
Rank (using tf.rank): 2


In [ ]:
#3d zeros tensor
zeros_tensor_3d= tf.zeros([2,3,2])
print("zeros tensor: \n",zeros_tensor_3d.numpy())

zeros tensor: 
 [[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [ ]:
# Attributes of 3D tensor
print("\nAttributes of Zeros Tensor:")
print("Number of Dimensions (ndim):", zeros_tensor_3d.ndim)
print("Shape:", zeros_tensor_3d.shape)
print("Number of Elements:", tf.size(zeros_tensor_3d).numpy())
print("Data Type:", zeros_tensor_3d.dtype)
print("Rank (using tf.rank):", tf.rank(zeros_tensor_3d).numpy())


Attributes of Zeros Tensor:
Number of Dimensions (ndim): 3
Shape: (2, 3, 2)
Number of Elements: 12
Data Type: <dtype: 'float32'>
Rank (using tf.rank): 3


In [ ]:
#4d zeros tensor
zeros_tensor_4d= tf.zeros([2,1,4,4])
print("zeros tensor: \n",zeros_tensor_4d.numpy())

zeros tensor: 
 [[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]]


In [ ]:
# Attributes of 4D tensor
print("\nAttributes of Zeros Tensor:")
print("Number of Dimensions (ndim):", zeros_tensor_4d.ndim)
print("Shape:", zeros_tensor_4d.shape)
print("Number of Elements:", tf.size(zeros_tensor_4d).numpy())
print("Data Type:", zeros_tensor_4d.dtype)
print("Rank (using tf.rank):", tf.rank(zeros_tensor_4d).numpy())



Attributes of Zeros Tensor:
Number of Dimensions (ndim): 4
Shape: (2, 1, 4, 4)
Number of Elements: 32
Data Type: <dtype: 'float32'>
Rank (using tf.rank): 4


### **The `tf.ones` function creates a tensor filled with ones, defined by a specific shape and data type.**

In [ ]:
#2d ones tensor
ones_tensor_2d= tf.ones([3,5])
print("ones tensor: \n",ones_tensor_2d.numpy())

ones tensor: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Attributes of 2D ones tensor
print("\nAttributes of Ones Tensor (2D):")
print("Number of Dimensions (ndim):", ones_tensor_2d.ndim)
print("Shape:", ones_tensor_2d.shape)
print("Number of Elements:", tf.size(ones_tensor_2d).numpy())
print("Data Type:", ones_tensor_2d.dtype)
print("Rank (using tf.rank):", tf.rank(ones_tensor_2d).numpy())


Attributes of Ones Tensor (2D):
Number of Dimensions (ndim): 2
Shape: (3, 5)
Number of Elements: 15
Data Type: <dtype: 'float32'>
Rank (using tf.rank): 2


In [ ]:
#3d ones tensor
ones_tensor_3d= tf.ones([2,3,2])
print("ones tensor: \n",ones_tensor_3d.numpy())

ones tensor: 
 [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [ ]:
# Attributes of 3D ones tensor
print("\nAttributes of Ones Tensor (3D):")
print("Number of Dimensions (ndim):", ones_tensor_3d.ndim)
print("Shape:", ones_tensor_3d.shape)
print("Number of Elements:", tf.size(ones_tensor_3d).numpy())
print("Data Type:", ones_tensor_3d.dtype)
print("Rank (using tf.rank):", tf.rank(ones_tensor_3d).numpy())


Attributes of Ones Tensor (3D):
Number of Dimensions (ndim): 3
Shape: (2, 3, 2)
Number of Elements: 12
Data Type: <dtype: 'float32'>
Rank (using tf.rank): 3


In [ ]:
#4d ones tensor
ones_tensor_4d= tf.ones([2,1,4,4])
print("ones tensor: \n",ones_tensor_4d.numpy())

ones tensor: 
 [[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]]


In [ ]:
# Attributes of 4D ones tensor
print("\nAttributes of Ones Tensor (4D):")
print("Number of Dimensions (ndim):", ones_tensor_4d.ndim)
print("Shape:", ones_tensor_4d.shape)
print("Number of Elements:", tf.size(ones_tensor_4d).numpy())
print("Data Type:", ones_tensor_4d.dtype)
print("Rank (using tf.rank):", tf.rank(ones_tensor_4d).numpy())


Attributes of Ones Tensor (4D):
Number of Dimensions (ndim): 4
Shape: (2, 1, 4, 4)
Number of Elements: 32
Data Type: <dtype: 'float32'>
Rank (using tf.rank): 4


ndim: The number of dimensions (axes) in the tensor.

shape: A tuple representing the size of each dimension of the tensor.

dtype: The data type of the elements in the tensor.

tf.size(): The total number of elements in the tensor.

tf.rank(): The rank (number of dimensions) of the tensor.