**Slicing in Tensorflow:**

In [77]:
import tensorflow as tf

In [78]:
t1= tf.constant([0,1,2,3,4,5,6,7,8,9])

In [79]:
t1

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [80]:
tf.slice(t1, begin=[3], size=[5])  #begin refers to staring of index and size is the number of elements

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([3, 4, 5, 6, 7], dtype=int32)>

In [81]:
tf.slice(t1, begin=[3], size=[2])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>

In [103]:
#slicing on a matrix
t2 = tf.constant([[0, 1, 2],
				[3, 4, 5],
				[6, 7, 8]])
t2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [102]:
# Get the first row
print('First Row:\n', t2[2])

# Get the second column
print('\nSecond columns:\n', t2[:,1])

# Get the second and third columns
print('\nSecond & Third columns:\n', t2[:, 1:3])

First Row:
 tf.Tensor([6 7 8], shape=(3,), dtype=int32)

Second columns:
 tf.Tensor([1 4 7], shape=(3,), dtype=int32)

Second & Third columns:
 tf.Tensor(
[[1 2]
 [4 5]
 [7 8]], shape=(3, 2), dtype=int32)


**tf.gather: Extracting tensors**

In [84]:
t3= tf.constant([3,2,4,2,5,2,4,5,3])
t3.numpy()

array([3, 2, 4, 2, 5, 2, 4, 5, 3], dtype=int32)

In [85]:
#extract specific elements from indexes
tf.gather(t3, indices=[3,7]).numpy()

array([2, 5], dtype=int32)

In [86]:
t4= tf.constant([[2,1,3],
				[4,0,5],
				[6,8,7]])
t4.numpy()

array([[2, 1, 3],
       [4, 0, 5],
       [6, 8, 7]], dtype=int32)

In [87]:
tf.gather(t4, indices=[1,2]).numpy()  #rows

array([[4, 0, 5],
       [6, 8, 7]], dtype=int32)

In [88]:
tf.gather(t4, indices=[1,2], axis=1).numpy()  #columns

array([[1, 3],
       [0, 5],
       [8, 7]], dtype=int32)

**Comparison with Slicing and Gathering:**

Slicing is great for continuous ranges, like extracting a slice of rows or columns.

tf.gather is more flexible when you need non-contiguous or specific elements/rows/columns, especially when the selection is not sequential.

In [101]:
#3d tensor
t5 = tf.constant([[[1, 3, 5, 7],
				[9, 11, 13, 15]],
				[[17, 19, 21, 23],
				[25, 27, 29, 31]]])
t5

<tf.Tensor: shape=(2, 2, 4), dtype=int32, numpy=
array([[[ 1,  3,  5,  7],
        [ 9, 11, 13, 15]],

       [[17, 19, 21, 23],
        [25, 27, 29, 31]]], dtype=int32)>

In [90]:
Indices = [[0, 0, 0], [1, 1, 1], [1, 0, 3]]
special_picks = tf.gather_nd(t5, indices=Indices, batch_dims=0)
special_picks.numpy()

array([ 1, 27, 23], dtype=int32)

In [100]:
Indices = [[0, 1, 1], [1, 1, 3], [0, 0, 3]]
special_picks = tf.gather_nd(t5, indices=Indices, batch_dims=0)
special_picks.numpy()

array([11, 31,  7], dtype=int32)

**The `tf.scatter_nd` function in TensorFlow is used to create a new tensor by updating specific elements at given indices with provided values, effectively "scattering" these updates across a tensor of a specified shape.**

In [92]:
t6 = tf.zeros(shape=(4, 5))
t6

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [93]:
#specifying indexes
Index = [[0, 0],
		[1, 1],
		[2, 2]]

In [94]:
#specifying the values
values = [100, 200, 300]

In [95]:
t6 = tf.scatter_nd(indices=Index,
				updates=values,
				shape=t6.shape)
t6.numpy()

array([[100,   0,   0,   0,   0],
       [  0, 200,   0,   0,   0],
       [  0,   0, 300,   0,   0],
       [  0,   0,   0,   0,   0]], dtype=int32)

In [96]:
t6 = tf.ones(shape=(5, 4))
print(t6)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(5, 4), dtype=float32)


In [97]:
#specifying indexes
Index = [[0, 1],
		[2, 2],
		[3, 3]]

In [98]:
#specifying the values
values = [11, 22, 33]

In [99]:
t6 = tf.scatter_nd(indices=Index,
				updates=values,
				shape=t6.shape)
t6.numpy()

array([[ 0, 11,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0, 22,  0],
       [ 0,  0,  0, 33],
       [ 0,  0,  0,  0]], dtype=int32)