**Reshaping Tensors:**

syntax: tf.reshape(tensor, shape, name=None)

In [48]:
import tensorflow as tf

In [49]:
#create a tensor
t1= tf.constant([[5,3,7],[2,4,6]])
t1.numpy()

array([[5, 3, 7],
       [2, 4, 6]], dtype=int32)

In [50]:
tf.shape(t1).numpy()

array([2, 3], dtype=int32)

In [51]:
#Reshaping to a 1D Tensor

In [52]:
t2 = tf.reshape(t1, [6]) #[6] indicates that the output tensor should have a single dimension with 6 elements
t2.numpy()

array([5, 3, 7, 2, 4, 6], dtype=int32)

In [53]:
#Reshaping to 2d tensor

In [54]:
t3 = tf.reshape(t2, [1,6])
t3.numpy()

array([[5, 3, 7, 2, 4, 6]], dtype=int32)

In [55]:
t4 = tf.reshape(t2, [2,3])
t4.numpy()

array([[5, 3, 7],
       [2, 4, 6]], dtype=int32)

In [56]:
t5 = tf.reshape(t2, [3,2])
t5.numpy()

array([[5, 3],
       [7, 2],
       [4, 6]], dtype=int32)

In [57]:
#Creating a 3d tensor

In [59]:
sequence_tensor = tf.range(27)
sequence_tensor.numpy()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26], dtype=int32)

In [60]:
t6= tf.reshape(sequence_tensor, [3,3,3])
t6.numpy()

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]], dtype=int32)

**Transpose** changes the order of dimensions, while **reshaping** changes the shape of the tensor without altering its data order.

**Using Transposition Operations to Reshape:**

Transposing the tensor with tf.transpose() changes the arrangement of dimensions

In [61]:
#Transposing a 2D tensor

In [62]:
t7= tf.constant([[1,1,1],[2,2,2]])
t7.numpy()

array([[1, 1, 1],
       [2, 2, 2]], dtype=int32)

In [63]:
t8 = tf.transpose(t7)
t8.numpy()

array([[1, 2],
       [1, 2],
       [1, 2]], dtype=int32)

In [64]:
#Transposing a 3D tensor

In [65]:
t9 = tf.constant([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
t9.numpy()

array([[[1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4]]], dtype=int32)

In [66]:
t10 = tf.transpose(t9)
t10.numpy()

array([[[1, 3],
        [2, 4]],

       [[1, 3],
        [2, 4]],

       [[1, 3],
        [2, 4]]], dtype=int32)

In [67]:
t10 = tf.transpose(t9, perm=[2, 0, 1])
# perm: List of integers representing the new order of the dimensions.
# Example: perm=[2, 0, 1] will move the original 3rd dimension to 1st place,
# the 1st dimension to 2nd place, and the 2nd dimension to 3rd place.

t10.numpy()

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]], dtype=int32)

The [-1] argument indicates that the output tensor should be reshaped into a 1D tensor (vector) where TensorFlow infers the size of one dimension based on the total number of elements in the original tensor. In other words, it flattens the original 2D tensor into a 1D tensor.

In [68]:
t11= tf.reshape(t7, [-1])
t11.numpy()

array([1, 1, 1, 2, 2, 2], dtype=int32)