**Bitwise Operations:**

In [1]:
import tensorflow as tf


tensor1 = tf.constant([0, 1, 0, 1], dtype=tf.int32)
tensor1.numpy()

array([0, 1, 0, 1], dtype=int32)

In [2]:
tensor2 = tf.constant([1, 0, 1, 0], dtype=tf.int32)
tensor2.numpy()

array([1, 0, 1, 0], dtype=int32)

In [3]:
# Bitwise AND
bitwise_and = tf.bitwise.bitwise_and(tensor1, tensor2)
print("Bitwise AND:\n", bitwise_and.numpy())


Bitwise AND:
 [0 0 0 0]


In [4]:
# Bitwise OR
bitwise_or = tf.bitwise.bitwise_or(tensor1, tensor2)
print("Bitwise OR:\n", bitwise_or.numpy())

Bitwise OR:
 [1 1 1 1]


In [5]:
# Bitwise XOR
bitwise_xor = tf.bitwise.bitwise_xor(tensor1, tensor2)
print("Bitwise XOR:\n", bitwise_xor.numpy())

Bitwise XOR:
 [1 1 1 1]


**Tensor Broadcasting** in TensorFlow is a technique that allows tensors with **different shapes** to be used in arithmetic operations together.

In [6]:
#shape (3, 1)
tensor3 = tf.constant([[1], [2], [3]], dtype=tf.float32)

#shape (1, 4)
tensor4 = tf.constant([[4, 5, 6, 7]], dtype=tf.float32)

In [7]:
#Same dimesnion different shapes

In [8]:
tf.add(tensor3, tensor4).numpy()  #broadcasting!

array([[ 5.,  6.,  7.,  8.],
       [ 6.,  7.,  8.,  9.],
       [ 7.,  8.,  9., 10.]], dtype=float32)

**Addition result:**

For each element in tensor1 added to the corresponding element in tensor2:

First row: 1+4, 1+5, 1+6, 1+7 → [5, 6, 7, 8]

Second row: 2+4, 2+5, 2+6, 2+7 → [6, 7, 8, 9]

Third row: 3+4, 3+5, 3+6, 3+7 → [7, 8, 9, 10]

**Broadcasting with substraction:**

In [9]:
tensor5 = tf.constant([[10], [20], [30]], dtype=tf.float32)  # Shape (3, 1)
tensor5.numpy()

array([[10.],
       [20.],
       [30.]], dtype=float32)

In [10]:
tensor6 = tf.constant([[1, 2, 3, 4]], dtype=tf.float32)  # Shape (1, 4)
tensor6.numpy()

array([[1., 2., 3., 4.]], dtype=float32)

In [11]:
tf.subtract(tensor5, tensor6).numpy()

array([[ 9.,  8.,  7.,  6.],
       [19., 18., 17., 16.],
       [29., 28., 27., 26.]], dtype=float32)

**Broadcasting with Multiplication:**

In [12]:
tensor7 = tf.constant([[1, 2, 3]], dtype=tf.float32)  # Shape (1, 3)
tensor7.numpy()

array([[1., 2., 3.]], dtype=float32)

In [13]:
tensor8 = tf.constant([[4], [5], [6]], dtype=tf.float32)  # Shape (3, 1)
tensor8.numpy()

array([[4.],
       [5.],
       [6.]], dtype=float32)

In [14]:
tf.multiply(tensor7, tensor8).numpy()

array([[ 4.,  8., 12.],
       [ 5., 10., 15.],
       [ 6., 12., 18.]], dtype=float32)

**Broadcasting with Division**

In [15]:
t1 = tf.constant([[100], [200]], dtype=tf.float32)  # Shape (2, 1)
t1.numpy()

array([[100.],
       [200.]], dtype=float32)

In [16]:
t2 = tf.constant([[10, 20, 30]], dtype=tf.float32)  # Shape (1, 3)
t2.numpy()

array([[10., 20., 30.]], dtype=float32)

In [17]:
tf.divide(t1, t2).numpy()

array([[10.       ,  5.       ,  3.3333333],
       [20.       , 10.       ,  6.6666665]], dtype=float32)

*tf.random.Generator* which is a powerful tool for managing random number generation

In [18]:
# Create a generator with a specific seed
generator = tf.random.Generator.from_seed(42)

# Generate random numbers using the generator
r_numbers = generator.normal(shape=(4, 2))

print(r_numbers)

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]
 [ 0.09988727 -0.50998646]], shape=(4, 2), dtype=float32)


In [21]:
r_numbers2 = generator.normal(shape=(3,2))
print(r_numbers2)  #different numbers

tf.Tensor(
[[ 0.6284844 -0.7251966]
 [-0.9048978 -0.638548 ]
 [-2.1893945  1.9348295]], shape=(3, 2), dtype=float32)
