# **tf.math in Tensorflow:**

In [179]:
import tensorflow as tf

In [180]:
t1= tf.constant([2,4,6], dtype= tf.float32)
t1.numpy()

array([2., 4., 6.], dtype=float32)

In [181]:
t2= tf.constant([8,10,12], dtype = tf.float32)
t2.numpy()

array([ 8., 10., 12.], dtype=float32)

In [182]:
# 1. Addition

In [183]:
tf.math.add(t1,t2).numpy()

array([10., 14., 18.], dtype=float32)

In [184]:
# 2. Subtraction

In [185]:
tf.math.subtract(t2,t1).numpy()

array([6., 6., 6.], dtype=float32)

In [186]:
# 3. Multiplication

In [187]:
tf.math.multiply(t1,t2).numpy()

array([16., 40., 72.], dtype=float32)

In [188]:
# 4. Division

In [189]:
tf.math.divide(t2,t1).numpy()

array([4. , 2.5, 2. ], dtype=float32)

In [190]:
# 5. Square Root

In [191]:
tf.math.sqrt(t1).numpy()

array([1.4142135, 2.       , 2.4494898], dtype=float32)

In [192]:
# 6. Logarithm

In [193]:
tf.math.log(t2).numpy()

array([2.0794415, 2.3025851, 2.4849067], dtype=float32)

In [194]:
# 7. Maximum Value

In [195]:
tf.math.reduce_max(t2).numpy()

12.0

In [196]:
# 8. Sum of tensor

In [197]:
tf.math.reduce_sum(t1).numpy()  #2+4+6

12.0

In [198]:
 # 9. Argmax (index of max value)

In [199]:
tf.math.argmax(t2).numpy()

2

In [200]:
# 10. cosine of tensor

In [201]:
tf.math.cos(t2).numpy()

array([-0.14550003, -0.8390715 ,  0.84385395], dtype=float32)

In [202]:
# 11. Exponentiation

In [203]:
tf.math.exp(t1).numpy()

array([  7.389056,  54.59815 , 403.4288  ], dtype=float32)

In [204]:
# 12. Power

In [205]:
tf.math.pow(t2, 4).numpy() # we can write t1 inplace of 4 too

array([ 4096., 10000., 20736.], dtype=float32)

In [206]:
tensor = tf.constant([-3.5, -2.2, 0.0, 2.2, 3.5], dtype=tf.float32)

In [207]:
# 13. Ceil

In [208]:
tf.math.ceil(tensor).numpy()

array([-3., -2.,  0.,  3.,  4.], dtype=float32)

In [209]:
# 14. floor

In [210]:
tf.math.floor(tensor).numpy()

array([-4., -3.,  0.,  2.,  3.], dtype=float32)

In [211]:
# 15. Round

In [212]:
tf.math.round(tensor).numpy()

array([-4., -2.,  0.,  2.,  4.], dtype=float32)

**Generating Random Tensors:**

In [213]:
t3= tf.random.uniform(shape=[2,3], maxval=10, dtype=tf.float32)
t3.numpy()

array([[6.8789124, 4.8447886, 9.309944 ],
       [2.5218701, 7.3115396, 8.925682 ]], dtype=float32)

In [214]:
t4 = tf.random.uniform(shape=[4,5], maxval= 100, dtype= tf.int32)
t4.numpy()

array([[ 4, 92, 77, 24, 23],
       [ 7, 84, 19, 12, 27],
       [61, 74, 62, 94, 27],
       [ 9, 87, 69, 33, 14]], dtype=int32)

**Without a Seed:** Every time you run the code, TensorFlow will generate different random numbers.

**With a Seed:** The same "random" numbers are generated every time you run the code, as long as the seed value remains the same.

In [215]:
rt1 = tf.random.uniform(shape=[3, 2], maxval=10, dtype=tf.int32)
rt1.numpy()

array([[4, 0],
       [4, 4],
       [2, 0]], dtype=int32)

In [216]:
rt2 = tf.random.uniform(shape=[3, 2], maxval=10, dtype=tf.int32)
rt2.numpy()

array([[9, 5],
       [8, 8],
       [3, 8]], dtype=int32)

In [217]:
tf.random.set_seed(42)

rt3 = tf.random.uniform(shape=[3, 2], maxval=10, dtype=tf.int32)
rt3.numpy()


array([[7, 9],
       [1, 6],
       [2, 4]], dtype=int32)

In [218]:
tf.random.set_seed(42)

rt4 = tf.random.uniform(shape=[3, 2], maxval=10, dtype=tf.int32)
rt4.numpy()

array([[7, 9],
       [1, 6],
       [2, 4]], dtype=int32)